### ISSUE TITLE
replay error: state.AppHash does not match AppHash after replay

### ISSUE THREAD

**Issue by jokernguyen921731** [hyperledger/burrow#1391]
Hello guys, my problem comes out when I stop a node and start it again

**Describe the Bug**
when I send amount of transactions:
```
Using validator address: 2EA57322BE82261F883DA250FBCBF23B97B29D75
length mempool 1
length mempool 0
length mempool 1
length mempool 0
length mempool 4
length mempool 95
length mempool 45
```
I break a node suddenly and start it again, the system return a error like this:
```
Using validator address: 2EA57322BE82261F883DA250FBCBF23B97B29D75
panic: Tendermint state.AppHash does not match AppHash after replay. Got 8A826BE861F929EDDAE40646601C99FF24AA33CE4678E13037A238010F29F445555718BC53D95B1B92478E3C3CAF717D96743C3A23E5BE5FAF2374199D2F6C9E, expected 3EAF0A5D08DAA3484E04C5C206282B104F60E0FAA16BED888442CEA858AFAD30E3DA76C45E6F1A5AD55DE5FBBA95CEDF88EEA1ABB481A6F8B7A9C4BE47124842 [recovered]
	panic: Tendermint state.AppHash does not match AppHash after replay. Got 8A826BE861F929EDDAE40646601C99FF24AA33CE4678E13037A238010F29F445555718BC53D95B1B92478E3C3CAF717D96743C3A23E5BE5FAF2374199D2F6C9E, expected 3EAF0A5D08DAA3484E04C5C206282B104F60E0FAA16BED888442CEA858AFAD30E3DA76C45E6F1A5AD55DE5FBBA95CEDF88EEA1ABB481A6F8B7A9C4BE47124842

goroutine 1 [running]:
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0009b5f50, 0x10cec20, 0xc0008a7310)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:39 +0xda
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0009b5fb0, 0x10cec20, 0xc0008a7310)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xc2
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0009e8b10, 0x10cec20, 0xc0008a7310)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xc2
github.com/jawher/mow.cli/internal/flow.(*Step).callDo.func1(0xc0009e8b40, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:52 +0x4a
panic(0x10cec20, 0xc0008a7310)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/tendermint/tendermint/consensus.checkAppHash(0xa, 0x0, 0xc000137156, 0x6, 0xc001e80680, 0x14, 0x6d2a, 0x621aa, 0xc001942200, 0x40, ...)
	/home/bapvn/go/pkg/mod/gitlab-new.bap.jp/!b!l!o!c!k!c!h!a!i!n/tendermint@v0.31.90/consensus/replay.go:461 +0x188
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc000cd7018, 0xa, 0x0, 0xc000137156, 0x6, 0xc001e80680, 0x14, 0x6d2a, 0x621aa, 0xc001942200, ...)
	/home/bapvn/go/pkg/mod/gitlab-new.bap.jp/!b!l!o!c!k!c!h!a!i!n/tendermint@v0.31.90/consensus/replay.go:437 +0x2f8
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000cd7018, 0xa, 0x0, 0xc000137156, 0x6, 0xc001e80680, 0x14, 0x6d2a, 0x621aa, 0xc001942200, ...)
	/home/bapvn/go/pkg/mod/gitlab-new.bap.jp/!b!l!o!c!k!c!h!a!i!n/tendermint@v0.31.90/consensus/replay.go:358 +0xa47
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000cd7018, 0x1611420, 0xc000955260, 0x2, 0x15fd5e0)
	/home/bapvn/go/pkg/mod/gitlab-new.bap.jp/!b!l!o!c!k!c!h!a!i!n/tendermint@v0.31.90/consensus/replay.go:264 +0x537
github.com/tendermint/tendermint/node.NewNode(0xc000399680, 0x15f3d20, 0xc001d588e0, 0xc000125b90, 0x15d52c0, 0xc001ebfe80, 0xc000cd72c0, 0xc000cd72b0, 0xc000125a50, 0x15fd5e0, ...)
	/home/bapvn/go/pkg/mod/gitlab-new.bap.jp/!b!l!o!c!k!c!h!a!i!n/tendermint@v0.31.90/node/node.go:266 +0x9e6
github.com/tendermint/xek-core-blockchain/consensus/tendermint.NewNode(0xc000399680, 0x15f3d20, 0xc001d588e0, 0xc00038a380, 0xc0000c0780, 0xc000125a50, 0xc001cb0f78, 0xc0015d26c0, 0x0, 0x15d5980, ...)
	/home/bapvn/go/src/github.com/tendermint/xek-core-blockchain/consensus/tendermint/tendermint.go:72 +0x3f5
github.com/tendermint/xek-core-blockchain/core.(*Kernel).LoadTendermintFromConfig(0xc0008c2240, 0xc0009e61e0, 0x15f3d20, 0xc001d588e0, 0x15f3d20, 0xc001d588e0)
	/home/bapvn/go/src/github.com/tendermint/xek-core-blockchain/core/config.go:103 +0x9e5
github.com/tendermint/xek-core-blockchain/core.LoadKernelFromConfig(0xc0009e61e0, 0x12f782a, 0x1b, 0xc000a0f0e0)
	/home/bapvn/go/src/github.com/tendermint/xek-core-blockchain/core/config.go:142 +0x53a
github.com/tendermint/xek-core-blockchain/cmd/burrow/commands.Start.func1.1()
	/home/bapvn/go/src/github.com/tendermint/xek-core-blockchain/cmd/burrow/commands/start.go:25 +0x229
github.com/jawher/mow.cli/internal/flow.(*Step).callDo(0xc0009e8b40, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:55 +0x7b
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0009e8b40, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:25 +0x43
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0009e8ae0, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xc2
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc0009b5f80, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xc2
github.com/jawher/mow.cli/internal/flow.(*Step).Run(0xc00093fec8, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/internal/flow/flow.go:29 +0xc2
github.com/jawher/mow%2ecli.(*Cmd).parse(0xc000187400, 0xc00003c1a0, 0x1, 0x1, 0xc00093fec8, 0xc0009b5f80, 0xc0009b5fb0, 0x203000, 0x7)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/commands.go:681 +0x50e
github.com/jawher/mow%2ecli.(*Cmd).parse(0xc000187300, 0xc00003c190, 0x2, 0x2, 0xc00093fec8, 0xc00093fec8, 0xc0009b5f50, 0x30, 0x120bfe0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/commands.go:695 +0x74b
github.com/jawher/mow%2ecli.(*Cli).parse(0xc0009e0280, 0xc00003c190, 0x2, 0x2, 0xc00093fec8, 0xc00093fec8, 0xc0009b5f50, 0x12fded8, 0x1f)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/cli.go:76 +0x13f
github.com/jawher/mow%2ecli.(*Cli).Run(0xc0009e0280, 0xc00003c180, 0x3, 0x3, 0x0, 0x0)
	/home/bapvn/go/pkg/mod/github.com/jawher/mow.cli@v1.1.0/cli.go:105 +0x144
main.main()
	/home/bapvn/go/src/github.com/tendermint/xek-core-blockchain/cmd/burrow/main.go:15 +0x76
```

**My opinion**
I believe the reason is not from tendermint, because I run tendermint alone and everything is fine. Maybe when burrow using iavl (https://github.com/tendermint/iavl) to calculate, it make the difference of apphash. If I remove the old db of that node, it is ok when I restart. However, I think the updating state process will waste a huge of time when orther nodes are at high height. So that is my temporary solution for now.

**Technical Details**
- [ ] Burrow Version v0.26.1
- [ ] Go Version v1.13
- [ ] Iavl Version v0.12.2

Any else solution for that?

**Comment by silasdavis** [comment]
Thanks for the report, can you provide the version you are using?

**Comment by silasdavis** [comment]
Memory is a little fuzzy, possibly the fix included in: https://github.com/hyperledger/burrow/releases/tag/v0.30.0 may be what you are seeing

**Comment by jokernguyen921731** [comment]
Now I'm using version 0.30.4 of burrow and seem the problem is solved. But when I test the stability by sending a lot of transactions in many hours, the other problem comes out:

**Comment by silasdavis** [comment]
Ah Tendermint's dreaded autofile. We've had some issues around this implementation before. Some older things: https://github.com/tendermint/tendermint/issues/890. To be fair this may be nothing to do with autofile.

It may be you do just need more file handles, you can try increasing file ulimits (see: https://www.linuxtechi.com/set-ulimit-file-descriptors-limit-linux-servers/). It may be we/Tendermint is holding open files it does not need to. I would need to look into that.

For memory issues the profiler is helpful (Golang pprof). It can be enabled in the config and Go ships with a webserver to look at memory dumps.

What we need in this area is a holistic stress test combined with some profiling to find out where we might be leaking memory. I am aware there are some issues lingering in state and IAVL in particular that are likely to contribute to memory issues. If you are able to pinpoint a specific leak then I could take a look. Unfortunately I don't have time to spend digging on this just now, but I hope to in the future.

**Comment by jokernguyen921731** [comment]
I hope this error can be fixed as soon as possible, anyway, thank for your response, I appreciate that!
