### ISSUE TITLE
Concurrency bug in Erismint state hashmap

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#354]
Reported concurrency bug on slack.monax.io

`````` "log":"fatal error: concurrent map read and map write\n","stream":"stderr","time":"2016-10-12T20:54:53.369556334Z"
{"log":"\n","stream":"stderr","time":"2016-10-12T20:54:53.373469366Z"}
{"log":"goroutine 3940664 [running]:\n","stream":"stderr","time":"2016-10-12T20:54:53.373494316Z"}
{"log":"runtime.throw(0x7f6d6069ccb0, 0x21)\n","stream":"stderr","time":"2016-10-12T20:54:53.373500903Z"}
{"log":"\u0009/usr/lib/go/src/runtime/panic.go:566 +0x97 fp=0xc4299d5648 sp=0xc4299d5628\n","stream":"stderr","time":"2016-10-12T20:54:53.373506346Z"}
{"log":"runtime.mapaccess1_faststr(0x7f6d60c65260, 0xc420f7d830, 0xc42a501340, 0x14, 0x14)\n","stream":"stderr","time":"2016-10-12T20:54:53.373512316Z"}
{"log":"\u0009/usr/lib/go/src/runtime/hashmap_fast.go:201 +0x4f5 fp=0xc4299d56a8 sp=0xc4299d5648\n","stream":"stderr","time":"2016-10-12T20:54:53.37351746Z"}
{"log":"github.com/eris-ltd/eris-db/manager/eris-mint/state.(*BlockCache).GetAccount(0xc420f7db00, 0xc42a501340, 0x14, 0x20, 0x7f6d60c093a0)\n","stream":"stderr","time":"2016-10-12T20:54:53.373538693Z"}
{"log":"\u0009/go/src/github.com/eris-ltd/eris-db/manager/eris-mint/state/block_cache.go:48 +0x80 fp=0xc4299d5720 sp=0xc4299d56a8\n","stream":"stderr","time":"2016-10-12T20:54:53.389565787Z"}
{"log":"github.com/eris-ltd/eris-db/manager/eris-mint.(*transactor).Transact(0xc42048ef50, 0xc42eaf9540, 0x40, 0x40, 0xc42a5012a0, 0x14, 0x14, 0xc424decff0, 0xe4, 0xe4, ...)\n","stream":"stderr","time":"2016-10-12T20:54:53.389601543Z"}
{"log":"\u0009/go/src/github.com/eris-ltd/eris-db/manager/eris-mint/transactor.go:174 +0x141 fp=0xc4299d57f0 sp=0xc4299d5720\n","stream":"stderr","time":"2016-10-12T20:54:53.38960935Z"}
{"log":"github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).handleTransact(0xc4204a3680, 0xc4339b3340)\n","stream":"stderr","time":"2016-10-12T20:54:53.389615443Z"}
{"log":"\u0009/go/src/github.com/eris-ltd/eris-db/rpc/v0/restServer.go:412 +0x386 fp=0xc4299d58a8 sp=0xc4299d57f0\n","stream":"stderr","time":"2016-10-12T20:54:53.389620853Z"}
{"log":"github.com/eris-ltd/eris-db/rpc/v0.(*RestServer).(github.com/eris-ltd/eris-db/rpc/v0.handleTransact)-fm(0xc4339b3340)\n","stream":"stderr","time":"2016-10-12T20:54:53.389626147Z"}
{"log":"\u0009/go/src/github.com/eris-ltd/eris-db/rpc/v0/restServer.go:85 +0x36 fp=0xc4299d58c8 sp=0xc4299d58a8\n","stream":"stderr","time":"2016-10-12T20:54:53.38963136Z"}```
``````

**Comment by ohhopi** [comment]
I don't know if this will help but i'm often having the same issue, i dumped my chains logs in a [gist](https://gist.github.com/ohhopi/197a8cf3b741f1c6d4be5af7322e4179).

A bit of context : 
- The chain i'm using has 6 .js files (using eris-contracts) all running simultaneously. 
- They are all listening to an "opening" event from a contract and all transact pretty much at the same time.
- Once they are all done transacting, the contract sends another event, prompting the contracts to transact once again and wait for another round.
- This process is repeated 6 times.
- The chain usually crashes after 3 or 4 rounds.

**Comment by benjaminbollen** [comment]
@ohhopi Is this a bug you've experienced on 0.11.4 (up to 0.12.0-rc2) or is it new since 0.12.0-rc3

**Comment by ohhopi** [comment]
@benjaminbollen I had the "fatal error: concurrent map writes" issue in 0.11.4 and thought it was fixed in 0.12.0-rc3.

**Comment by benjaminbollen** [comment]
clearly it has not been fixed (sufficiently) but it helps to know this relates to work done before.  Very useful;  do you have a skeleton to reproduce?  (js / solidity files; if not I can build it myself as part of the bug)

**Comment by Quiark** [comment]
We were also seeing this crash after using the chain for a long time (sending tx and stuff). Looks like the map is not properly protected for concurrent access.

**Comment by silasdavis** [comment]
completely rewritten
