### ISSUE TITLE
[rpc] [tests] low priority intermittent failure in rpc testing framework

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#370]
Intermittent failure in rpc tendermint tests, triggered in testframework; low priority;

https://circleci.com/gh/eris-ltd/eris-db/859:

```panic: Paniced on a Crisis: Could not write file /tmp/Eris-DB885519482/rootWorkDir/priv_validator.json.new. open /tmp/Eris-DB885519482/rootWorkDir/priv_validator.json.new: no such file or directory

goroutine 48 [running]:
panic(0xbcbc40, 0xc82018fec0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common.PanicCrisis(0xd0d840, 0xc82018fe90)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/go-common/errors.go:33 +0xf5
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/types.(*PrivValidator).save(0xc8204be880)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/types/priv_validator.go:148 +0x14f
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/types.(*PrivValidator).SignProposal(0xc8204be880, 0xc8200e8c00, 0x9, 0xc8221f0480, 0x0, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/types/priv_validator.go:194 +0xf8
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).decideProposal(0xc8200ac300, 0x5e, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:826 +0x23b
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterPropose(0xc8200ac300, 0x5e, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:803 +0xd7d
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterNewRound(0xc8200ac300, 0x5e, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:767 +0xbbb
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleTimeout(0xc8200ac300, 0x3b979374, 0x5e, 0x0, 0xc8221fea01, 0x5e, 0x0, 0x1, 0xecfb29b0e, 0xe71638a, ...)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:704 +0x890
github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc8200ac300, 0x0)
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:623 +0x580
created by github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).startRoutines
	/home/ubuntu/.go_workspace/src/github.com/eris-ltd/eris-db/vendor/github.com/tendermint/tendermint/consensus/state.go:320 +0x61
FAIL	github.com/eris-ltd/eris-db/rpc/tendermint/test	98.979s```

**Comment by silasdavis** [comment]
@benjaminbollen tempted to close this, since I think it will probably be superseded by RPC framework, but maybe worth a fix before then, or maybe we're going to be sticking with this manner of integration test for a while and the attendant timing issues? What do you think?

**Comment by compleatang** [comment]
Completely changed. Closing.
