### ISSUE TITLE
chain stops after a while - out of memory

### ISSUE THREAD

**Issue by marc4gov** [hyperledger/burrow#611]
- [0.16.2 ] `burrow version` (docker image tag or branch if built from source)
- [0.16 ] `monax version` (if applicable)
- [1.8] `go version` (if applicable)
- [17.04.0-ce] `docker version` (if applicable)
- [osx] operating system details (osx/windows/linux)

Expecting chain keeps running after several contract queries

- what actually happened

Chains stops after several big queries (fetching 40 addresses + info) with an `out of memory` log

- steps to reproduction

The big query takes about 10-14s to load from a call with the node js lib. I did it approx. 10 times, then the chain trips...

burrow log:

```
...
INFO[05-16|20:18:24] Block{
  Header{
    ChainID:        testchain
    Height:         1561
    Time:           2017-05-16 20:18:24.848 +0000 UTC
    NumTxs:         0
    LastBlockID:    D4660168D97091156E3DA4333BD3F100190BBACA:1:2997D433EB1A
    LastCommit:     9A43B07891C46CF7BB0810DF16C57F2CA6B7E9C4
    Data:           
    Validators:     22E5C16A78980085D39C98E26B3BCA1257D95849
    App:            570CC578D9A03D3248342CA59517349F7D600444
  }#E53F6F8B58C57C53001EC2610A00ADD83CBB1D77
  Data{
    
  }#
  Commit{
    BlockID:    D4660168D97091156E3DA4333BD3F100190BBACA:1:2997D433EB1A
    Precommits: Vote{0:04358DB6C90E 1560/00/2(Precommit) D4660168D970 /AD20AF4F1389.../}
  }#9A43B07891C46CF7BB0810DF16C57F2CA6B7E9C4
}#E53F6F8B58C57C53001EC2610A00ADD83CBB1D77 module=consensus
INFO[05-16|20:18:24] Executed block                           module=state height=1561 valid txs=0 invalid txs=0
INFO[05-16|20:18:24] Committing block                         channel=Info run_id=ed417f84-3a70-11e7-8e4d-aba367565962 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 burrow-mint.go:151 local_client.go:197 app_conn.go:81 execution.go:258 execution.go:243 state.go:1251 state.go:1198 state.go:1151 state.go:1178 state.go:1467 state.go:1356 state.go:699 state.go:655 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe BurrowMint]" last_block_height=1561
INFO[05-16|20:18:25] Resetting checkCache                     channel=Info run_id=ed417f84-3a70-11e7-8e4d-aba367565962 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 burrow-mint.go:158 local_client.go:197 app_conn.go:81 execution.go:258 execution.go:243 state.go:1251 state.go:1198 state.go:1151 state.go:1178 state.go:1467 state.go:1356 state.go:699 state.go:655 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe BurrowMint]" txs=0
INFO[05-16|20:18:25] Recheck txs                              module=mempool numtxs=0
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x55b2b12161d5, 0x16)
	/usr/lib/go/src/runtime/panic.go:566 +0x97
runtime.sysMap(0xc46ff50000, 0x100000, 0x55b20001a500, 0x55b2b1c4aab8)
	/usr/lib/go/src/runtime/mem_linux.go:219 +0x1d2
runtime.(*mheap).sysAlloc(0x55b2b1c30a20, 0x100000, 0x1f700000100)
	/usr/lib/go/src/runtime/malloc.go:407 +0x37c
runtime.(*mheap).grow(0x55b2b1c30a20, 0x80, 0x0)
	/usr/lib/go/src/runtime/mheap.go:726 +0x64
runtime.(*mheap).allocSpanLocked(0x55b2b1c30a20, 0x80, 0x8000)
	/usr/lib/go/src/runtime/mheap.go:630 +0x4f4
runtime.(*mheap).alloc_m(0x55b2b1c30a20, 0x80, 0x7f0100000000, 0x55b2b0b9070b)
	/usr/lib/go/src/runtime/mheap.go:515 +0xe4
runtime.(*mheap).alloc.func1()
	/usr/lib/go/src/runtime/mheap.go:579 +0x4d
runtime.systemstack(0x7febcd279d28)
	/usr/lib/go/src/runtime/asm_amd64.s:314 +0xa1
runtime.(*mheap).alloc(0x55b2b1c30a20, 0x80, 0x10100000000, 0x42)
	/usr/lib/go/src/runtime/mheap.go:580 +0x75
runtime.largeAlloc(0x100000, 0x7febcd72a001, 0xc400000042)
	/usr/lib/go/src/runtime/malloc.go:774 +0x95
runtime.mallocgc.func1()
	/usr/lib/go/src/runtime/malloc.go:669 +0x40
runtime.systemstack(0xc420018000)
	/usr/lib/go/src/runtime/asm_amd64.s:298 +0x72
runtime.mstart()
	/usr/lib/go/src/runtime/proc.go:1079

goroutine 6068 [running]:
runtime.systemstack_switch()
	/usr/lib/go/src/runtime/asm_amd64.s:252 fp=0xc44760c310 sp=0xc44760c308
runtime.mallocgc(0x100000, 0x55b2b17c5960, 0x1600180825b5601, 0xc46cbbc000)
	/usr/lib/go/src/runtime/malloc.go:670 +0x915 fp=0xc44760c3b0 sp=0xc44760c310
runtime.makeslice(0x55b2b17c5960, 0x100000, 0x100000, 0xc46cbbc000, 0x400, 0x400)
	/usr/lib/go/src/runtime/slice.go:57 +0x7d fp=0xc44760c408 sp=0xc44760c3b0
github.com/hyperledger/burrow/manager/burrow-mint/evm.(*VM).call(0xc4476175d0, 0xc459d17c80, 0xc459d17f00, 0xc46750a800, 0x10a5, 0x10a5, 0xc4659d15f8, 0x4, 0x4, 0x0, ...)
	/go/src/github.com/hyperledger/burrow/manager/burrow-mint/evm/vm.go:214 +0x43b fp=0xc447611b18 sp=0xc44760c408
github.com/hyperledger/burrow/manager/burrow-mint/evm.(*VM).Call(0xc4476175d0, 0xc459d17c80, 0xc459d17f00, 0xc46750a800, 0x10a5, 0x10a5, 0xc4659d15f8, 0x4, 0x4, 0x0, ...)
	/go/src/github.com/hyperledger/burrow/manager/burrow-mint/evm/vm.go:154 +0x22c fp=0xc447611bc8 sp=0xc447611b18
github.com/hyperledger/burrow/manager/burrow-mint/evm.(*VM).call(0xc4476175d0, 0xc459d17d00, 0xc459d17c80, 0xc467538000, 0x2fa4, 0x2fa4, 0xc4507424e0, 0x24, 0x24, 0x0, ...)
	/go/src/github.com/hyperledger/burrow/manager/burrow-mint/evm/vm.go:878 +0x1af2e fp=0xc4476172d8 sp=0xc447611bc8
github.com/hyperledger/burrow/manager/burrow-mint/evm.(*VM).Call(0xc4476175d0, 0xc459d17d00, 0xc459d17c80, 0xc467538000, 0x2fa4, 0x2fa4, 0xc4507424e0, 0x24, 0x24, 0x0, ...)
	/go/src/github.com/hyperledger/burrow/manager/burrow-mint/evm/vm.go:154 +0x22c fp=0xc447617388 sp=0xc4476172d8
github.com/hyperledger/burrow/manager/burrow-mint.(*transactor).Call(0xc420449b80, 0xc458f9b960, 0x14, 0x14, 0xc458f9b920, 0x14, 0x14, 0xc4507424e0, 0x24, 0x24, ...)
	/go/src/github.com/hyperledger/burrow/manager/burrow-mint/transactor.go:91 +0x863 fp=0xc447617678 sp=0xc447617388
github.com/hyperledger/burrow/rpc/v0.(*BurrowMethods).Call(0xc4202952f0, 0xc440dc1680, 0x55b2b18820a0, 0xc4643d7ef0, 0x3, 0x0, 0x0, 0xc42005b4d0, 0xc42420eec8)
	/go/src/github.com/hyperledger/burrow/rpc/v0/methods.go:338 +0x1d7 fp=0xc447617740 sp=0xc447617678
github.com/hyperledger/burrow/rpc/v0.(*BurrowMethods).Call-fm(0xc440dc1680, 0x55b2b18820a0, 0xc4643d7ef0, 0xc4643d7ef0, 0xc42005b570, 0x101, 0xc45f428fa8, 0xc45f428f28)
	/go/src/github.com/hyperledger/burrow/rpc/v0/methods.go:120 +0x4a fp=0xc447617798 sp=0xc447617740
github.com/hyperledger/burrow/rpc/v0.(*BurrowJsonService).Process(0xc420295290, 0xc464339770, 0x7febcc783e50, 0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/rpc/v0/json_service.go:115 +0x2bf fp=0xc447617828 sp=0xc447617798
github.com/hyperledger/burrow/rpc/v0.(*JsonRpcServer).handleFunc(0xc42028c800, 0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/rpc/v0/json_service.go:63 +0x9b fp=0xc447617878 sp=0xc447617828
github.com/hyperledger/burrow/rpc/v0.(*JsonRpcServer).(github.com/hyperledger/burrow/rpc/v0.handleFunc)-fm(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/rpc/v0/json_service.go:43 +0x36 fp=0xc447617898 sp=0xc447617878
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/context.go:97 +0x5c fp=0xc4476178b8 sp=0xc447617898
github.com/hyperledger/burrow/vendor/github.com/tommy351/gin-cors.Middleware.func1(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tommy351/gin-cors/cors.go:77 +0x1fe fp=0xc447617958 sp=0xc4476178b8
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/context.go:97 +0x5c fp=0xc447617978 sp=0xc447617958
github.com/hyperledger/burrow/server.contentTypeMW(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/server/server.go:251 +0x42 fp=0xc4476179e0 sp=0xc447617978
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/context.go:97 +0x5c fp=0xc447617a00 sp=0xc4476179e0
github.com/hyperledger/burrow/server.logHandler(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/server/server.go:223 +0x5f fp=0xc447617b10 sp=0xc447617a00
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/context.go:97 +0x5c fp=0xc447617b30 sp=0xc447617b10
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/recovery.go:45 +0x5c fp=0xc447617b60 sp=0xc447617b30
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Context).Next(0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/context.go:97 +0x5c fp=0xc447617b80 sp=0xc447617b60
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc420107ea0, 0xc4643d7ef0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/gin.go:284 +0x650 fp=0xc447617c78 sp=0xc447617b80
github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc420107ea0, 0x55b2b1bf5320, 0xc4365bfad0, 0xc464339770)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/gin-gonic/gin/gin.go:265 +0x132 fp=0xc447617cb0 sp=0xc447617c78
net/http.serverHandler.ServeHTTP(0xc420087f80, 0x55b2b1bf5320, 0xc4365bfad0, 0xc464339770)
	/usr/lib/go/src/net/http/server.go:2202 +0x7f fp=0xc447617cf8 sp=0xc447617cb0
net/http.(*conn).serve(0xc459d17b00, 0x55b2b1bf5fa0, 0xc44c47df40)
	/usr/lib/go/src/net/http/server.go:1579 +0x4b9 fp=0xc447617f58 sp=0xc447617cf8
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc447617f60 sp=0xc447617f58
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2293 +0x44f
...
```

If issue is a feature request, tell us why this feature is useful.

**Comment by marc4gov** [comment]
This is the output from `docker stats` on the burrow container (quite high on MEM, maybe that's the issue?)
```
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
77a18a6cefad        47.03%              752.2MiB / 995.8MiB   75.54%              4.58MB / 35.6MB     39.5GB / 7.91GB     10

```

**Comment by marc4gov** [comment]
When I stop the chain and try to start it again, I get this, most of the time. Chain dies....
```
INFO[06-03|20:42:55] Force disabling Tendermint's native RPC  channel=Info run_id=3876a542-489d-11e7-86d0-4df11b598c51 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 tendermint.go:118 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" provided_rpc_laddr=0.0.0.0:46657
panic: Paniced on a Sanity Check: Expected storeHeight (1756) and stateHeight (1755) to match.
```

**Comment by rpoddighe** [comment]
+1, experiencing the same issue. When deploying lots of contracts (either in parallel or in serial), the running burrow server's CPU and memory usage increases. On a server restart the CPU/memory usage returns to normal, however it is often not possible to restart then chain due to the aforementioned error. 
It could be related to this Tendermint issue:

https://github.com/tendermint/tendermint/issues/388 

This is claimed to be fixed in Tendermint v0.9.0 (Burrow currently uses 0.8 if I'm not mistaken).

**Comment by silasdavis** [comment]
This may be another manifestation of: https://github.com/hyperledger/burrow/pull/718
