### ISSUE TITLE
chain is unstable - stopping and starting 1 validator makes the validator trip

### ISSUE THREAD

**Issue by marc4gov** [hyperledger/burrow#615]
Please include in your bug report:

- [ 0.16.4] `burrow version` (docker image tag or branch if built from source)
- [0.16 ] `monax version` (if applicable)
- [1.8 ] `go version` (if applicable)
- [17.05 ] `docker version` (if applicable)
- [ linux] operating system details (osx/windows/linux)
- [ ] what you expected to happen
Stopping and starting 1 validator out of 4 should not be a problem
- [ ] what actually happened
Chain seems to keep running, but I can't get the stopped validator back on
- [ ] steps to reproduction
I have 4 validators in 1 datacenter stopping 1 validator and starting it again gives this:

Output log:
```
INFO[05-23|19:30:25] Block{
  Header{
    ChainID:        h2chain
    Height:         915
    Time:           2017-05-23 19:30:23.735 +0000 UTC
    NumTxs:         0
    LastBlockID:    8D7560AB1298CCC0F7A3C070C73EB03F4337B9D3:1:35FA48F4E9C3
    LastCommit:     D0D99670796E015D147DB1D7C6F567E05264FC2B
    Data:           
    Validators:     7B3C7282B178AD18DDB54DB2C4AE99BCBE78EFD2
    App:            CE289CE3AF8C437EBE3FCAC4787AD9C76C5E9B5D
  }#CECB83FAD52593197538F20783972DE01D75EA65
  Data{
    
  }#
  Commit{
    BlockID:    8D7560AB1298CCC0F7A3C070C73EB03F4337B9D3:1:35FA48F4E9C3
    Precommits: Vote{0:24E5FAC0E7BB 914/00/2(Precommit) 8D7560AB1298 /C7C2022D0503.../}
    nil-Vote
    Vote{2:4A1811F7BEDF 914/00/2(Precommit) 8D7560AB1298 /477354D591EB.../}
    Vote{3:648E0A5CCCE6 914/00/2(Precommit) 8D7560AB1298 /3077D6CA03A5.../}
  }#D0D99670796E015D147DB1D7C6F567E05264FC2B
}#CECB83FAD52593197538F20783972DE01D75EA65 module=consensus
INFO[05-23|19:30:25] Executed block                           module=state height=915 valid txs=0 invalid txs=0
INFO[05-23|19:30:25] Committing block                         channel=Info run_id=dfe7653b-3fe8-11e7-8d34-035e2d10acff trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 burrow-mint.go:151 local_client.go:197 app_conn.go:81 execution.go:258 execution.go:243 state.go:1251 state.go:1198 state.go:1151 state.go:1178 state.go:1467 state.go:1356 state.go:699 state.go:651 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe BurrowMint]" last_block_height=915
INFO[05-23|19:30:26] Server stop event fired. Good bye.       module=server
DBUG[05-23|19:31:10] Loading configuration for serve command  channel=Trace run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:133 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve chainId=h2chain workingDirectory=/home/monax/.monax/chains/h2chain dataDirectory=/home/monax/.monax/chains/h2chain/data genesisFile=/home/monax/.monax/chains/h2chain/genesis.json
DBUG[05-23|19:31:10] Modules configured                       channel=Trace run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:147 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve consensusModule=tendermint-0.8 applicationManager=burrowmint-0.16
DBUG[01-01|00:00:00] Starting EventSwitch                     channel=Info run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:142 service.go:93 core.go:52 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=events impl=EventSwitch
INFO[05-23|19:31:10] Loading BurrowMint                       channel=Info run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 manager.go:47 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]" compatibleConsensus=tendermint-0.8 burrowMintVersion=burrowmint-0.16.4
INFO[05-23|19:31:10] Loaded state                             channel=Info run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 pipe.go:83 manager.go:48 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=h2chain lastBlockHeight=914 lastBlockHash=
DBUG[05-23|19:31:10] Loaded pipe with application manager     channel=Trace run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 core.go:61 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]"
DBUG[05-23|19:31:10] Loaded Tendermint sub-configuration      channel=Trace run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 tendermint.go:103 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=h2chain genesisFile=/home/monax/.monax/chains/h2chain/genesis.json nodeLocalAddress=0.0.0.0:46656 moniker=h2chain_validator_002 seeds=51.15.37.82:46656,51.15.64.249:46656,51.15.66.82:46656,51.15.60.120:46656 fastSync=false rpcLocalAddress=0.0.0.0:46657 databaseDirectory=/home/monax/.monax/chains/h2chain/data/tendermint/data privateValidatorFile=/home/monax/.monax/chains/h2chain/priv_validator.json privValFile=priv_validator.json
DBUG[01-01|00:00:00] Loaded PrivValidator                     channel=Info run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:146 priv_validator.go:122 tendermint.go:110 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=types file=/home/monax/.monax/chains/h2chain/priv_validator.json privValidator="PrivValidator{24E5FAC0E7BBACAD4396B8C9698749C2602B13BA LH:915, LR:1, LS:3}"
INFO[05-23|19:31:10] Force disabling Tendermint's native RPC  channel=Info run_id=601b68cf-3fee-11e7-8c8a-43505b54dae5 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 tendermint.go:118 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" provided_rpc_laddr=0.0.0.0:46657
panic: Paniced on a Sanity Check: Expected storeHeight (915) and stateHeight (914) to match.

goroutine 1 [running]:
panic(0x555f3d3ef6e0, 0xc4201c3040)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.PanicSanity(0x555f3d3ef6e0, 0xc4201c3010)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/errors.go:26 +0xe2
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).ReplayBlocks(0xc420198c90, 0x0, 0x0, 0x0, 0x0, 0x555f3d822b00, 0xc4201c2e30, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:400 +0xda4
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).Handshake(0xc420198c90, 0x555f3d824200, 0xc4204be1b0, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:329 +0x485
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc4204be1b0, 0xc4201fcf60, 0x15)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:100 +0x208
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.(*BaseService).Start(0xc4204be1b0, 0xc4204be100, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/service.go:96 +0x548
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node.NewNode(0x555f3d824820, 0xc420024428, 0xc4204706e0, 0x555f3d816ca0, 0xc4204e2440, 0x2)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node/node.go:68 +0x485
github.com/hyperledger/burrow/consensus/tendermint.NewTendermint(0xc420074e10, 0x555f3d8222c0, 0xc4200e1e50, 0x555f3d820f40, 0xc4201df410, 0xc4201df410, 0x555f3c855baa, 0x555f3d818e60)
	/go/src/github.com/hyperledger/burrow/consensus/tendermint/tendermint.go:123 +0x114b
github.com/hyperledger/burrow/consensus.LoadConsensusEngineInPipe(0xc420074e10, 0x555f3d8248c0, 0xc420450b80, 0x24, 0x0)
	/go/src/github.com/hyperledger/burrow/consensus/consensus.go:30 +0x155
github.com/hyperledger/burrow/core.NewCore(0xc420016009, 0x7, 0xc420074e10, 0xc4200750e0, 0x555f3d820f40, 0xc4201df1e0, 0x4, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/core/core.go:63 +0x360
github.com/hyperledger/burrow/cmd.NewCoreFromDo(0xc42005b980, 0xc4200120cf, 0x21, 0x555f3ce31f2a)
	/go/src/github.com/hyperledger/burrow/cmd/serve.go:149 +0xa88
github.com/hyperledger/burrow/cmd.ServeRunner.func1(0xc42007dd40, 0x555f3d872830, 0x0, 0x0)
	/go/src/github.com/hyperledger/burrow/cmd/serve.go:167 +0xcb
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).execute(0xc42007dd40, 0x555f3d872830, 0x0, 0x0, 0xc42007dd40, 0x555f3d872830)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:575 +0x43b
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x555f3d80ecc0, 0x1, 0x1, 0xc42007dd40)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:661 +0x369
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).Execute(0x555f3d80ecc0, 0x0, 0xc420198270)
	/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:620 +0x2d
github.com/hyperledger/burrow/cmd.Execute()
	/go/src/github.com/hyperledger/burrow/cmd/burrow.go:46 +0x33d
main.main()
	/go/src/github.com/hyperledger/burrow/cmd/burrow/main.go:22 +0x16
```

**Comment by silasdavis** [comment]
Fixed on develop by Tendermint upgrade: https://github.com/hyperledger/burrow/pull/595
