### ISSUE TITLE
Chain getting stopped on transaction execution

### ISSUE THREAD

**Issue by ashlinSajan** [hyperledger/burrow#667]
##Tendermint  ## version 0.8

 ## Burrow-Mint ## version 0.16

**On below transaction execution chain got stopped.**

```
Commit{
    BlockID:    428C54FEC3AE006A45CFFFB3F4B97C31D5A28852:1:3B6E2E0FD9A0
    Precommits: Vote{0:3974B6BA812F 948/00/2(Precommit) 428C54FEC3AE /7E91A34537F3.../}
  }#7A3CD861DE35C02F239E7A5A4B0D9CB8595AA01F
}#4B524B032D3A5628735036D5E685320BBB1D8D43 module=consensus
INFO[01-01|04:37:22] Account has permission                   module=state address=3974B6BA812F915E59FDD11332ABF00EF97A36B8 perm=call
INFO[01-01|04:37:22] Out account: Account{5C1985894DFE860B8D767A0DE3DD554172D5163C:<nil> B:0 C:1202 S: P:{Base: 100011111110; Set: 11111111111111 []}} module=state
INFO[01-01|04:37:22] Calling contract 0000000000000000000000005C1985894DFE860B8D767A0DE3DD554172D5163C with code 60606040526000357C010000000000000000000000000000000000000000000000000000000090048063CD02F5641461003C57610037565B610002565B34610002576101476004808035906020019082018035906020019191908080601F016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050909091908035906020019091908035906020019091908035906020019082018035906020019191908080601F016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050909091908035906020019091908035906020019082018035906020019191908080601F01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190803590602001909190505061015F565B60405180821515815260200191505060405180910390F35B6000600115156002600050600089600019168152602001908152602001600020600050605E0160009054906101000A900460FF161515141561049F578560026000506000896000191681526020019081526020016000206000506000016000506000016000506000016000508190555084600260005060008960001916815260200190815260200160002060005060000160005060000160005060010160005083600A8110156100025790900160005B509080519060200190828054600181600116156101000203166002900490600052602060002090601F016020900481019282601F1061025957805160FF191683800117855561028A565B8280016001018555821561028A579182015B8281111561028957825182600050559160200191906001019061026B565B5B5090506102B59190610297565B808211156102B15760008181506000905550600101610297565B5090565B5050836002600050600089600019168152602001908152602001600020600050600001600050600001600050600B0160005083600A8110156100025790900160005B508190555082600260005060008960001916815260200190815260200160002060005060000160005060000160005060150160005083600A8110156100025790900160005B509080519060200190828054600181600116156101000203166002900490600052602060002090601F016020900481019282601F1061038657805160FF19168380011785556103B7565B828001600101855582156103B7579182015B828111156103B6578251826000505591602001919060010190610398565B5B5090506103E291906103C4565B808211156103DE57600081815060009055506001016103C4565B5090565B50508560006000506000896000191681526020019081526020016000206000506000016000508190555060016002600050600089600019168152602001908152602001600020600050605E0160016101000A81548160FF02191690837F01000000000000000000000000000000000000000000000000000000000000009081020402179055506002600050600088600019168152602001908152602001600020600050605E0160019054906101000A900460FF16905080506104A6565B6000905080505B5B97965050505050505056 module=state
INFO[01-01|04:37:22] Code for this contract: 60606040526000357C010000000000000000000000000000000000000000000000000000000090048063CD02F5641461003C57610037565B610002565B34610002576101476004808035906020019082018035906020019191908080601F016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050909091908035906020019091908035906020019091908035906020019082018035906020019191908080601F016020809104026020016040519081016040528093929190818152602001838380828437820191505050505050909091908035906020019091908035906020019082018035906020019191908080601F01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190803590602001909190505061015F565B60405180821515815260200191505060405180910390F35B6000600115156002600050600089600019168152602001908152602001600020600050605E0160009054906101000A900460FF161515141561049F578560026000506000896000191681526020019081526020016000206000506000016000506000016000506000016000508190555084600260005060008960001916815260200190815260200160002060005060000160005060000160005060010160005083600A8110156100025790900160005B509080519060200190828054600181600116156101000203166002900490600052602060002090601F016020900481019282601F1061025957805160FF191683800117855561028A565B8280016001018555821561028A579182015B8281111561028957825182600050559160200191906001019061026B565B5B5090506102B59190610297565B808211156102B15760008181506000905550600101610297565B5090565B5050836002600050600089600019168152602001908152602001600020600050600001600050600001600050600B0160005083600A8110156100025790900160005B508190555082600260005060008960001916815260200190815260200160002060005060000160005060000160005060150160005083600A8110156100025790900160005B509080519060200190828054600181600116156101000203166002900490600052602060002090601F016020900481019282601F1061038657805160FF19168380011785556103B7565B828001600101855582156103B7579182015B828111156103B6578251826000505591602001919060010190610398565B5B5090506103E291906103C4565B808211156103DE57600081815060009055506001016103C4565B5090565B50508560006000506000896000191681526020019081526020016000206000506000016000508190555060016002600050600089600019168152602001908152602001600020600050605E0160016101000A81548160FF02191690837F01000000000000000000000000000000000000000000000000000000000000009081020402179055506002600050600088600019168152602001908152602001600020600050605E0160019054906101000A900460FF16905080506104A6565B6000905080505B5B97965050505050505056 module=state
panic: runtime error: slice bounds out of range

goroutine 51 [running]:
panic(0x55c8d82dbca0, 0xc4200160c0)
/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/hyperledger/burrow/manager/burrow-mint/evm.(*VM).call(0xc424584be8, 0xc423b18980, 0xc423b18a00, 0xc421ac3400, 0x4b2, 0x4b2, 0xc424554480, 0x204, 0x204, 0x0, ...)
/go/src/github.com/hyperledger/burrow/manager/burrow-mint/evm/vm.go:530 +0x57b7
github.com/hyperledger/burrow/manager/burrow-mint/evm.(*VM).Call(0xc424584be8, 0xc423b18980, 0xc423b18a00, 0xc421ac3400, 0x4b2, 0x4b2, 0xc424554480, 0x204, 0x204, 0x0, ...)
/go/src/github.com/hyperledger/burrow/manager/burrow-mint/evm/vm.go:154 +0x22c
github.com/hyperledger/burrow/manager/burrow-mint/state.ExecTx(0xc4201c2fc0, 0x55c8d86c0ba0, 0xc423af2960, 0xc424564601, 0x55c8d86c1b20, 0xc4201c30b0, 0xc42415ed10, 0x55c8d8275080)
/go/src/github.com/hyperledger/burrow/manager/burrow-mint/state/execution.go:502 +0x6084
github.com/hyperledger/burrow/manager/burrow-mint.(*BurrowMint).DeliverTx(0xc4204a7a40, 0xc424181340, 0x2b1, 0x2b1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/manager/burrow-mint/burrow-mint.go:110 +0x1a1
github.com/hyperledger/burrow/vendor/github.com/tendermint/abci/client.(*localClient).DeliverTxAsync(0xc42011a4e0, 0xc424181340, 0x2b1, 0x2b1, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/abci/client/local_client.go:74 +0x87
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0xc420181a40, 0xc424181340, 0x2b1, 0x2b1, 0xc423b127e0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy/app_conn.go:73 +0x53
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x7f4705c60328, 0xc423b10a80, 0x55c8d86cdb00, 0xc420181a40, 0xc42046d280, 0x0, 0x0, 0x0, 0x28, 0x55c8d7e6ce63)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:116 +0x4e1
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*State).ExecBlock(0xc423b1c420, 0x7f4705c60328, 0xc423b10a80, 0x55c8d86cdb00, 0xc420181a40, 0xc42046d280, 0x1, 0xc4201617c0, 0x14, 0x20, ...)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:38 +0x151
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*State).ApplyBlock(0xc423b1c420, 0x7f4705c60328, 0xc423b10a80, 0x55c8d86cdb00, 0xc420181a40, 0xc42046d280, 0x1, 0xc4201617c0, 0x14, 0x20, ...)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:237 +0xb7
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc420219040, 0x3b5)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:1251 +0xb64
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc420219040, 0x3b5)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:1198 +0x179
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc420219040, 0x0, 0x3b5)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:1151 +0x9f
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc420219040, 0x3b5, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:1178 +0x748
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc420219040, 0xc423b47c80, 0x0, 0x0, 0xc4204ad298, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:1467 +0x9e1
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc420219040, 0xc423b47c80, 0x0, 0x0, 0x20, 0x55c8d830d860)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:1356 +0x69
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc420219040, 0x55c8d82c97c0, 0xc420462e00, 0x0, 0x0, 0x3b5, 0x0, 0x6, 0xed1dbb202, 0x23f8088b, ...)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:699 +0x668
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc420219040, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:655 +0x460
created by github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/consensus/state.go:389 +0x55b




**when tried to call another contract it gives below error (seems error is due to chain got stopped).**


Burrow error:  Call of method "eventPoll" with parameters { sub_id: '412843E0D559BF3CC82837EE16F13FB13CF01C7314E7AE01C0520E053575E419' } responded with "Error: connect ECONNREFUSED 127.0.0.1:1337".
(node:9561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32969): TypeError: Cannot read property 'args' of undefined
Burrow error:  Call of method "eventPoll" with parameters { sub_id: '4C59506BA9269F04B464616E4F2ABE797B64256C630979B61EDBBDF897DB1E64' } responded with "Error: connect ECONNREFUSED 127.0.0.1:1337".
(node:9561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32970): TypeError: Cannot read property 'args' of undefined
Burrow error:  Call of method "eventPoll" with parameters { sub_id: 'D83066652A467CFB5A02BF6627CF60B9198DACF67F414CDE8095594D5E94A5D8' } responded with "Error: connect ECONNREFUSED 127.0.0.1:1337".
(node:9561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32971): TypeError: Cannot read property 'args' of undefined
Burrow error:  Call of method "eventPoll" with parameters { sub_id: '412843E0D559BF3CC82837EE16F13FB13CF01C7314E7AE01C0520E053575E419' } responded with "Error: connect ECONNREFUSED 127.0.0.1:1337".
(node:9561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32972): TypeError: Cannot read property 'args' of undefined
Burrow error:  Call of method "eventPoll" with parameters { sub_id: '4C59506BA9269F04B464616E4F2ABE797B64256C630979B61EDBBDF897DB1E64' } responded with "Error: connect ECONNREFUSED 127.0.0.1:1337".
(node:9561) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32973): TypeError: Cannot read property 'args' of undefined




**Below is the error log which got when tried to restart the chain**


DBUG[01-01|07:41:30] Loading configuration for serve command  channel=Trace run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:133 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve chainId=bchain workingDirectory=/home/monax/.monax/chains/bchain dataDirectory=/home/monax/.monax/chains/bchain/data genesisFile=/home/monax/.monax/chains/bchain/genesis.json
DBUG[01-01|07:41:30] Modules configured                       channel=Trace run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 info_trace_logger.go:139 convention.go:60 serve.go:147 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve consensusModule=tendermint-0.8 applicationManager=burrowmint-0.16
DBUG[01-01|00:00:00] Starting EventSwitch                     channel=Info run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:142 service.go:93 core.go:52 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=events impl=EventSwitch
INFO[01-01|07:41:30] Loading BurrowMint                       channel=Info run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 manager.go:47 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]" compatibleConsensus=tendermint-0.8 burrowMintVersion=burrowmint-0.16.3
INFO[01-01|07:41:30] Loaded state                             channel=Info run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 pipe.go:83 manager.go:48 core.go:57 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=bchain lastBlockHeight=948 lastBlockHash=
DBUG[01-01|07:41:30] Loaded pipe with application manager     channel=Trace run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 core.go:61 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core]"
DBUG[01-01|07:41:30] Loaded Tendermint sub-configuration      channel=Trace run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:130 convention.go:35 log.go:143 convention.go:60 convention.go:45 tendermint.go:103 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" chainId=bchain genesisFile=/home/monax/.monax/chains/bchain/genesis.json nodeLocalAddress=0.0.0.0:46656 moniker=bchain_full_000 seeds= fastSync=false rpcLocalAddress=0.0.0.0:46657 databaseDirectory=/home/monax/.monax/chains/bchain/data/tendermint/data privateValidatorFile=/home/monax/.monax/chains/bchain/priv_validator.json privValFile=priv_validator.json
DBUG[01-01|00:00:00] Loaded PrivValidator                     channel=Info run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 capture.go:43 handler_go14.go:14 handler_go14.go:14 logger.go:120 logger.go:146 priv_validator.go:122 tendermint.go:110 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope=Serve captured_logging_source=tendermint_log15 module=types file=/home/monax/.monax/chains/bchain/priv_validator.json privValidator="PrivValidator{3974B6BA812F915E59FDD11332ABF00EF97A36B8 LH:949, LR:0, LS:3}"
INFO[01-01|07:41:30] Force disabling Tendermint's native RPC  channel=Info run_id=2e8331ab-eec7-11e7-874f-be6eee4f30a7 trace="[metadata.go:46 value.go:19 log.go:84 info_trace_logger.go:126 convention.go:30 log.go:143 convention.go:60 convention.go:40 tendermint.go:118 consensus.go:30 core.go:63 serve.go:149 serve.go:167 command.go:575 command.go:661 command.go:620 burrow.go:46 main.go:22 proc.go:183 asm_amd64.s:2086]" scope="[Serve Core BurrowMintPipe]" provided_rpc_laddr=0.0.0.0:46657
panic: Paniced on a Sanity Check: Expected storeHeight (949) and stateHeight (948) to match.

goroutine 1 [running]:
panic(0x560b852756e0, 0xc4201e7260)
/usr/lib/go/src/runtime/panic.go:500 +0x1a5
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.PanicSanity(0x560b852756e0, 0xc4201e7230)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/errors.go:26 +0xe2
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).ReplayBlocks(0xc4201bdbf0, 0x0, 0x0, 0x0, 0x0, 0x560b856a8b00, 0xc4201e7080, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:400 +0xda4
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state.(*Handshaker).Handshake(0xc4201bdbf0, 0x560b856aa200, 0xc420086240, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/state/execution.go:329 +0x485
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc420086240, 0xc4201e4a60, 0x15)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/proxy/multi_app_conn.go:100 +0x208
github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common.(*BaseService).Start(0xc420086240, 0x0, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/go-common/service.go:96 +0x548
github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node.NewNode(0x560b856aa820, 0xc42011a338, 0xc4204f00a0, 0x560b8569cca0, 0xc4201b92c0, 0x2)
/go/src/github.com/hyperledger/burrow/vendor/github.com/tendermint/tendermint/node/node.go:68 +0x485
github.com/hyperledger/burrow/consensus/tendermint.NewTendermint(0xc42013cab0, 0x560b856a82c0, 0xc4204989b0, 0x560b856a6f40, 0xc4201f70b0, 0xc4201f70b0, 0x560b846dbbaa, 0x560b8569ee60)
/go/src/github.com/hyperledger/burrow/consensus/tendermint/tendermint.go:123 +0x114b
github.com/hyperledger/burrow/consensus.LoadConsensusEngineInPipe(0xc42013cab0, 0x560b856aa8c0, 0xc420454800, 0x24, 0x0)
/go/src/github.com/hyperledger/burrow/consensus/consensus.go:30 +0x155
github.com/hyperledger/burrow/core.NewCore(0xc420016009, 0x6, 0xc42013cab0, 0xc42013cd80, 0x560b856a6f40, 0xc420214d90, 0x4, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/core/core.go:63 +0x360
github.com/hyperledger/burrow/cmd.NewCoreFromDo(0xc420120f00, 0xc4200120cf, 0x20, 0x560b84cb7f2a)
/go/src/github.com/hyperledger/burrow/cmd/serve.go:149 +0xa88
github.com/hyperledger/burrow/cmd.ServeRunner.func1(0xc420158d80, 0x560b856f8830, 0x0, 0x0)
/go/src/github.com/hyperledger/burrow/cmd/serve.go:167 +0xcb
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).execute(0xc420158d80, 0x560b856f8830, 0x0, 0x0, 0xc420158d80, 0x560b856f8830)
/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:575 +0x43b
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x560b85694cc0, 0x1, 0x1, 0xc420158d80)
/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:661 +0x369
github.com/hyperledger/burrow/vendor/github.com/spf13/cobra.(*Command).Execute(0x560b85694cc0, 0x0, 0xc4204d9d70)
/go/src/github.com/hyperledger/burrow/vendor/github.com/spf13/cobra/command.go:620 +0x2d
github.com/hyperledger/burrow/cmd.Execute()
/go/src/github.com/hyperledger/burrow/cmd/burrow.go:46 +0x33d
main.main()
/go/src/github.com/hyperledger/burrow/cmd/burrow/main.go:22 +0x16
```

**Comment by silasdavis** [comment]
Fixed by: https://github.com/hyperledger/burrow/pull/704 - we now recover from panic, and bounds checking has been strengthened (protecting against negative offsets and overflows).
